import Head from 'next/head'
import { useAuth } from '@/lib/auth'
import { Button, Code, Flex, Text } from '@chakra-ui/react'
import Logo from '@/icons/Logo'

export default function Home() {
  const auth = useAuth()
  return (
    <Flex
      as="main"
      direction="column"
      align="center"
      justify="center"
      h="100vh"
    >
      <Head>
        <title>FeedYouBack</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Logo boxSize="64px" />

      {auth.user ? (
        <Button onClick={e => auth.signOutWithGithub()}>Sign out</Button>
      ) : (
        <Button mt={4} size="sm" onClick={e => auth.signInWithGithub()}>
          Sign In
        </Button>
      )}
    </Flex>
  )
}
